In [1]:
import numpy as np

sentence = ["What", "are", "the", "symptoms", "of", "diabetes", "?"]
seq_len = len(sentence)
d_k = 4

X = np.array([
    [0.1, 1.0, 0.2, 0.3],
    [0.1, 0.2, 1.0, 0.1],
    [0.0, 0.0, 0.1, 1.0],
    [0.9, 0.3, 0.1, 0.1],
    [0.0, 0.0, 0.1, 0.9],
    [0.9, 0.2, 0.1, 0.2],
    [0.1, 0.8, 0.1, 0.1],
])

np.random.seed(42)
W_Q = np.random.randn(d_k, d_k) * 0.5
W_K = np.random.randn(d_k, d_k) * 0.5
W_V = np.random.randn(d_k, d_k) * 0.5

Q = X @ W_Q
K = X @ W_K
V = X @ W_V

scores = Q @ K.T / np.sqrt(d_k)

def softmax(x):
    e = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return e / e.sum(axis=-1, keepdims=True)

attention_weights = softmax(scores)

output = attention_weights @ V

print("Sentence tokens:", sentence)
print()
print("Q matrix (7x4):")
print(np.round(Q, 3))
print()
print("K matrix (7x4):")
print(np.round(K, 3))
print()
print("Raw scores QK^T / sqrt(dk) (7x7):")
print(np.round(scores, 3))
print()
print("Attention Weights after Softmax (7x7):")
print(np.round(attention_weights, 3))
print()
print("Verify rows sum to 1.0:")
print(np.round(attention_weights.sum(axis=1), 4))
print()
print("Highest-attention token for each query:")
for i, token in enumerate(sentence):
    j = np.argmax(attention_weights[i])
    print(f"  {token!r:12} -> attends most to {sentence[j]!r}  (weight = {attention_weights[i, j]:.4f})")
print()
print("Self-Attention Output (shape:", output.shape, "):")
print(np.round(output, 3))

Sentence tokens: ['What', 'are', 'the', 'symptoms', 'of', 'diabetes', '?']

Q matrix (7x4):
[[-0.103 -0.357  0.517  0.329]
 [-0.221  0.145 -0.128 -0.108]
 [ 0.098 -0.93  -0.886 -0.304]
 [ 0.177 -0.166  0.419  0.749]
 [ 0.085 -0.834 -0.799 -0.276]
 [ 0.201 -0.25   0.254  0.683]
 [-0.08  -0.169  0.555  0.332]]

K matrix (7x4):
[[ 0.538 -0.13  -0.217 -0.468]
 [-0.206  0.034 -0.644  0.067]
 [-0.328 -0.14  -0.358  0.945]
 [-0.293  0.099 -0.486 -0.738]
 [-0.298 -0.126 -0.328  0.852]
 [-0.396  0.095 -0.52  -0.574]
 [ 0.478 -0.084 -0.106 -0.529]]

Raw scores QK^T / sqrt(dk) (7x7):
[[-0.137 -0.151  0.105 -0.249  0.093 -0.225 -0.124]
 [-0.03   0.063 -0.002  0.11  -0.001  0.115 -0.024]
 [ 0.254  0.249  0.064  0.267  0.06   0.254  0.19 ]
 [-0.162 -0.131  0.261 -0.412  0.235 -0.367 -0.171]
 [ 0.228  0.225  0.057  0.243  0.053  0.23   0.171]
 [-0.117 -0.084  0.262 -0.355  0.235 -0.314 -0.136]
 [-0.148 -0.162  0.082 -0.254  0.073 -0.231 -0.129]]

Attention Weights after Softmax (7x7):
[[0.136 0.134 0